name: flutter_jailbreak_detection_example
description: "Demonstrates how to use the flutter_jailbreak_detection plugin."
homepage: https://github.com/jeroentrappers/flutter_jailbreak_detection

publish_to: 'none'

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_jailbreak_detection:
    path: ../

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
